name: EPG Update
 
on:
  push:
  schedule:
    - cron: 0 * * * *

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: EPG Update
      run: |
        rm -f e.xml && wget https://epg.112114.xyz/pp.xml -O e.xml
        git config --global user.email "2969225395@qq.com"
        git config --global user.name "biansty"
        git add e.xml
        git commit -m "Update e.xml"
        git push -f origin master 
